language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"

env:
  - GO111MODULE=on COMPOSE_FILE=test/docker-compose.yml

services:
  - docker

script:
  - docker-compose up -d
  - docker-compose ps
  - make test-integration